### ISSUE TITLE
Standing close to crystals seems to be able to kill you in creative mode

### ISSUE THREAD

**Issue by TheDeviantCrafter** [disconsented/Cristallum#4]
When standing on a crystal in creative mode, sometimes you will lose the ability to move or interact with items. This issue is fixed when leaving and joining the world, but JourneyMap places a death marker. This suggests I am dead according to the server, but alive according to the client, and when reloading the world the server corrects itself. You are fully alive when you return to the world again.

**Comment by disconsented** [comment]
Is this on a remote server or a local world?

**Comment by TheDeviantCrafter** [comment]
Singleplayer. I was able to replicate it with only Cristallum, Quark and JEI installed.
